# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.2"
manifest_format = "2.0"
project_hash = "bdc78d860405830838f5524429bf09bb739312b4"

[[deps.EasyMonad]]
git-tree-sha1 = "2f821a8c3bc23144c8b4f260eb8a11376c1667e3"
repo-rev = "main"
repo-url = "https://github.com/overshiki/EasyMonad.jl.git"
uuid = "e4dbf12b-b8cf-4673-b6eb-8b0d4667dd49"
version = "0.1.0"

[[deps.NestedVector]]
deps = ["EasyMonad"]
git-tree-sha1 = "51ded2f7ac45a953ce8073b4b734b13397747f89"
repo-rev = "main"
repo-url = "https://github.com/overshiki/NestedVector.jl.git"
uuid = "03826054-d4ac-482b-9e88-e171687816a8"
version = "0.1.0"
