# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.1"
manifest_format = "2.0"

[[deps.NestedArray]]
git-tree-sha1 = "6e4092f29247438b91ef6fdeebd67f2dcd96e2e4"
repo-rev = "main"
repo-url = "https://github.com/overshiki/NestedArray.jl.git"
uuid = "03826054-d4ac-482b-9e88-e171687816a8"
version = "0.1.0"
